version: "3.9"

services:
  frontend:
    build: .
    container_name: frontend_frontend
    command: streamlit run src/app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
